# Header

menu:
  主页: /
  所有文章: /archives
  #随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/JayZangwill"
  #weibo: "#"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/zhang-jie-24-34-16"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /blog/touxiang.ico

#你的头像url
avatar: /blog/touxiang.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 
duoshuo: zj123
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: false
  tagcloud: '标签'
  friends: false
  aboutme: '关于我'

aboutme: 点这里<a href="http://jayzangwill.github.io/home#about">关于我